"""made debts dynamic 

Revision ID: 9d235ae9a6be
Revises: 3c9e12e75063
Create Date: 2024-07-15 06:36:56.858589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d235ae9a6be'
down_revision = '3c9e12e75063'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('total_amount_due')
        batch_op.drop_column('total_debtors')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_debtors', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('total_amount_due', sa.FLOAT(), nullable=False))

    # ### end Alembic commands ###
